/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or editor to prevent it from being shown or used.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutRoute } from './routes/(public)/_layout'
import { Route as AuthLayoutRoute } from './routes/(auth)/_layout'
import { Route as IndexRoute } from './routes/index'
import { Route as PublicSignInRoute } from './routes/(public)/sign-in'
import { Route as PublicSignUpRoute } from './routes/(public)/sign-up'
import { Route as AuthTabsLayoutRoute } from './routes/(auth)/(tabs)/_layout'
import { Route as AuthTabsOrdersIndexRoute } from './routes/(auth)/(tabs)/orders/index'
import { Route as AuthTabsMenuIndexRoute } from './routes/(auth)/(tabs)/menu/index'
import { Route as AuthTabsPaymentsIndexRoute } from './routes/(auth)/(tabs)/payments/index'
import { Route as AuthTabsGuestOrderIndexRoute } from './routes/(auth)/(tabs)/guest-order/index'
import { Route as AuthTabsProfileIndexRoute } from './routes/(auth)/(tabs)/profile/index'
import { Route as AuthTabsMenuAddMealRoute } from './routes/(auth)/(tabs)/menu/add-meal'
import { Route as AuthTabsProfileEditRoute } from './routes/(auth)/(tabs)/profile/edit'
import { Route as AuthTabsProfileSettingsRoute } from './routes/(auth)/(tabs)/profile/settings'
import { Route as AuthTabsProfileCategoriesRoute } from './routes/(auth)/(tabs)/profile/categories'
import { Route as AuthTabsProfileDailyReportRoute } from './routes/(auth)/(tabs)/profile/daily-report'
import { Route as AuthTabsOrdersDetailsIdRoute } from './routes/(auth)/(tabs)/orders/details/$id'
import { Route as AuthTabsPaymentsReceiptIdRoute } from './routes/(auth)/(tabs)/payments/receipt/$id'
import { Route as AuthTabsProfileUsersIndexRoute } from './routes/(auth)/(tabs)/profile/users/index'
import { Route as AuthTabsProfileMembershipIndexRoute } from './routes/(auth)/(tabs)/profile/membership/index'
import { Route as AuthTabsProfileUsersAddUserRoute } from './routes/(auth)/(tabs)/profile/users/add-user'
import { Route as AuthTabsProfileMembershipPaywallRoute } from './routes/(auth)/(tabs)/profile/membership/paywall'
import { Route as AuthPathnameRoute } from './routes/auth.$pathname'
import { Route as AccountPathnameRoute } from './routes/account.$pathname'

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutRoute.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutRoute.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexRoute.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicSignInRoute = PublicSignInRoute.update({
  path: '/sign-in',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicSignUpRoute = PublicSignUpRoute.update({
  path: '/sign-up',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const AuthTabsLayoutRoute = AuthTabsLayoutRoute.update({
  id: '/(tabs)',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthTabsOrdersIndexRoute = AuthTabsOrdersIndexRoute.update({
  path: '/orders/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsMenuIndexRoute = AuthTabsMenuIndexRoute.update({
  path: '/menu/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsPaymentsIndexRoute = AuthTabsPaymentsIndexRoute.update({
  path: '/payments/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsGuestOrderIndexRoute = AuthTabsGuestOrderIndexRoute.update({
  path: '/guest-order/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileIndexRoute = AuthTabsProfileIndexRoute.update({
  path: '/profile/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsMenuAddMealRoute = AuthTabsMenuAddMealRoute.update({
  path: '/menu/add-meal',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileEditRoute = AuthTabsProfileEditRoute.update({
  path: '/profile/edit',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileSettingsRoute = AuthTabsProfileSettingsRoute.update({
  path: '/profile/settings',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileCategoriesRoute = AuthTabsProfileCategoriesRoute.update({
  path: '/profile/categories',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileDailyReportRoute = AuthTabsProfileDailyReportRoute.update({
  path: '/profile/daily-report',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsOrdersDetailsIdRoute = AuthTabsOrdersDetailsIdRoute.update({
  path: '/orders/details/$id',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsPaymentsReceiptIdRoute = AuthTabsPaymentsReceiptIdRoute.update({
  path: '/payments/receipt/$id',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileUsersIndexRoute = AuthTabsProfileUsersIndexRoute.update({
  path: '/profile/users/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileMembershipIndexRoute = AuthTabsProfileMembershipIndexRoute.update({
  path: '/profile/membership/',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileUsersAddUserRoute = AuthTabsProfileUsersAddUserRoute.update({
  path: '/profile/users/add-user',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthTabsProfileMembershipPaywallRoute = AuthTabsProfileMembershipPaywallRoute.update({
  path: '/profile/membership/paywall',
  getParentRoute: () => AuthTabsLayoutRoute,
} as any)

const AuthPathnameRoute = AuthPathnameRoute.update({
  path: '/auth/$pathname',
  getParentRoute: () => rootRoute,
} as any)

const AccountPathnameRoute = AccountPathnameRoute.update({
  path: '/account/$pathname',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRoute
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRoute
      parentRoute: typeof rootRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRoute
      parentRoute: typeof PublicLayoutRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRoute
      parentRoute: typeof PublicLayoutRoute
    }
    '/(auth)/(tabs)': {
      id: '/(auth)/(tabs)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthTabsLayoutRoute
      parentRoute: typeof AuthLayoutRoute
    }
    '/(auth)/(tabs)/orders/': {
      id: '/(auth)/(tabs)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthTabsOrdersIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/menu/': {
      id: '/(auth)/(tabs)/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthTabsMenuIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/payments/': {
      id: '/(auth)/(tabs)/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthTabsPaymentsIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/guest-order/': {
      id: '/(auth)/(tabs)/guest-order/'
      path: '/guest-order'
      fullPath: '/guest-order'
      preLoaderRoute: typeof AuthTabsGuestOrderIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/': {
      id: '/(auth)/(tabs)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthTabsProfileIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/menu/add-meal': {
      id: '/(auth)/(tabs)/menu/add-meal'
      path: '/menu/add-meal'
      fullPath: '/menu/add-meal'
      preLoaderRoute: typeof AuthTabsMenuAddMealRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/edit': {
      id: '/(auth)/(tabs)/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthTabsProfileEditRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/settings': {
      id: '/(auth)/(tabs)/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthTabsProfileSettingsRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/categories': {
      id: '/(auth)/(tabs)/profile/categories'
      path: '/profile/categories'
      fullPath: '/profile/categories'
      preLoaderRoute: typeof AuthTabsProfileCategoriesRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/daily-report': {
      id: '/(auth)/(tabs)/profile/daily-report'
      path: '/profile/daily-report'
      fullPath: '/profile/daily-report'
      preLoaderRoute: typeof AuthTabsProfileDailyReportRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/orders/details/$id': {
      id: '/(auth)/(tabs)/orders/details/$id'
      path: '/orders/details/$id'
      fullPath: '/orders/details/$id'
      preLoaderRoute: typeof AuthTabsOrdersDetailsIdRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/payments/receipt/$id': {
      id: '/(auth)/(tabs)/payments/receipt/$id'
      path: '/payments/receipt/$id'
      fullPath: '/payments/receipt/$id'
      preLoaderRoute: typeof AuthTabsPaymentsReceiptIdRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/users/': {
      id: '/(auth)/(tabs)/profile/users/'
      path: '/profile/users'
      fullPath: '/profile/users'
      preLoaderRoute: typeof AuthTabsProfileUsersIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/membership/': {
      id: '/(auth)/(tabs)/profile/membership/'
      path: '/profile/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof AuthTabsProfileMembershipIndexRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/users/add-user': {
      id: '/(auth)/(tabs)/profile/users/add-user'
      path: '/profile/users/add-user'
      fullPath: '/profile/users/add-user'
      preLoaderRoute: typeof AuthTabsProfileUsersAddUserRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/(auth)/(tabs)/profile/membership/paywall': {
      id: '/(auth)/(tabs)/profile/membership/paywall'
      path: '/profile/membership/paywall'
      fullPath: '/profile/membership/paywall'
      preLoaderRoute: typeof AuthTabsProfileMembershipPaywallRoute
      parentRoute: typeof AuthTabsLayoutRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRoute
      parentRoute: typeof rootRoute
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthTabsLayoutRouteChildren {
  AuthTabsOrdersIndexRoute: typeof AuthTabsOrdersIndexRoute
  AuthTabsMenuIndexRoute: typeof AuthTabsMenuIndexRoute
  AuthTabsPaymentsIndexRoute: typeof AuthTabsPaymentsIndexRoute
  AuthTabsGuestOrderIndexRoute: typeof AuthTabsGuestOrderIndexRoute
  AuthTabsProfileIndexRoute: typeof AuthTabsProfileIndexRoute
  AuthTabsMenuAddMealRoute: typeof AuthTabsMenuAddMealRoute
  AuthTabsProfileEditRoute: typeof AuthTabsProfileEditRoute
  AuthTabsProfileSettingsRoute: typeof AuthTabsProfileSettingsRoute
  AuthTabsProfileCategoriesRoute: typeof AuthTabsProfileCategoriesRoute
  AuthTabsProfileDailyReportRoute: typeof AuthTabsProfileDailyReportRoute
  AuthTabsOrdersDetailsIdRoute: typeof AuthTabsOrdersDetailsIdRoute
  AuthTabsPaymentsReceiptIdRoute: typeof AuthTabsPaymentsReceiptIdRoute
  AuthTabsProfileUsersIndexRoute: typeof AuthTabsProfileUsersIndexRoute
  AuthTabsProfileMembershipIndexRoute: typeof AuthTabsProfileMembershipIndexRoute
  AuthTabsProfileUsersAddUserRoute: typeof AuthTabsProfileUsersAddUserRoute
  AuthTabsProfileMembershipPaywallRoute: typeof AuthTabsProfileMembershipPaywallRoute
}

const AuthTabsLayoutRouteChildren: AuthTabsLayoutRouteChildren = {
  AuthTabsOrdersIndexRoute: AuthTabsOrdersIndexRoute,
  AuthTabsMenuIndexRoute: AuthTabsMenuIndexRoute,
  AuthTabsPaymentsIndexRoute: AuthTabsPaymentsIndexRoute,
  AuthTabsGuestOrderIndexRoute: AuthTabsGuestOrderIndexRoute,
  AuthTabsProfileIndexRoute: AuthTabsProfileIndexRoute,
  AuthTabsMenuAddMealRoute: AuthTabsMenuAddMealRoute,
  AuthTabsProfileEditRoute: AuthTabsProfileEditRoute,
  AuthTabsProfileSettingsRoute: AuthTabsProfileSettingsRoute,
  AuthTabsProfileCategoriesRoute: AuthTabsProfileCategoriesRoute,
  AuthTabsProfileDailyReportRoute: AuthTabsProfileDailyReportRoute,
  AuthTabsOrdersDetailsIdRoute: AuthTabsOrdersDetailsIdRoute,
  AuthTabsPaymentsReceiptIdRoute: AuthTabsPaymentsReceiptIdRoute,
  AuthTabsProfileUsersIndexRoute: AuthTabsProfileUsersIndexRoute,
  AuthTabsProfileMembershipIndexRoute: AuthTabsProfileMembershipIndexRoute,
  AuthTabsProfileUsersAddUserRoute: AuthTabsProfileUsersAddUserRoute,
  AuthTabsProfileMembershipPaywallRoute: AuthTabsProfileMembershipPaywallRoute,
}

const AuthTabsLayoutRouteWithChildren = AuthTabsLayoutRoute._addFileChildren(AuthTabsLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthTabsLayoutRoute: typeof AuthTabsLayoutRouteWithChildren
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthTabsLayoutRoute: AuthTabsLayoutRouteWithChildren,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(AuthLayoutRouteChildren)

interface PublicLayoutRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(PublicLayoutRouteChildren)

interface FileRoutesByFullPath {
  '/': typeof AuthTabsLayoutRouteWithChildren
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/orders': typeof AuthTabsOrdersIndexRoute
  '/menu': typeof AuthTabsMenuIndexRoute
  '/payments': typeof AuthTabsPaymentsIndexRoute
  '/guest-order': typeof AuthTabsGuestOrderIndexRoute
  '/profile': typeof AuthTabsProfileIndexRoute
  '/menu/add-meal': typeof AuthTabsMenuAddMealRoute
  '/profile/edit': typeof AuthTabsProfileEditRoute
  '/profile/settings': typeof AuthTabsProfileSettingsRoute
  '/profile/categories': typeof AuthTabsProfileCategoriesRoute
  '/profile/daily-report': typeof AuthTabsProfileDailyReportRoute
  '/orders/details/$id': typeof AuthTabsOrdersDetailsIdRoute
  '/payments/receipt/$id': typeof AuthTabsPaymentsReceiptIdRoute
  '/profile/users': typeof AuthTabsProfileUsersIndexRoute
  '/profile/membership': typeof AuthTabsProfileMembershipIndexRoute
  '/profile/users/add-user': typeof AuthTabsProfileUsersAddUserRoute
  '/profile/membership/paywall': typeof AuthTabsProfileMembershipPaywallRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/account/$pathname': typeof AccountPathnameRoute
}

interface FileRoutesByTo {
  '/': typeof AuthTabsLayoutRouteWithChildren
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/orders': typeof AuthTabsOrdersIndexRoute
  '/menu': typeof AuthTabsMenuIndexRoute
  '/payments': typeof AuthTabsPaymentsIndexRoute
  '/guest-order': typeof AuthTabsGuestOrderIndexRoute
  '/profile': typeof AuthTabsProfileIndexRoute
  '/menu/add-meal': typeof AuthTabsMenuAddMealRoute
  '/profile/edit': typeof AuthTabsProfileEditRoute
  '/profile/settings': typeof AuthTabsProfileSettingsRoute
  '/profile/categories': typeof AuthTabsProfileCategoriesRoute
  '/profile/daily-report': typeof AuthTabsProfileDailyReportRoute
  '/orders/details/$id': typeof AuthTabsOrdersDetailsIdRoute
  '/payments/receipt/$id': typeof AuthTabsPaymentsReceiptIdRoute
  '/profile/users': typeof AuthTabsProfileUsersIndexRoute
  '/profile/membership': typeof AuthTabsProfileMembershipIndexRoute
  '/profile/users/add-user': typeof AuthTabsProfileUsersAddUserRoute
  '/profile/membership/paywall': typeof AuthTabsProfileMembershipPaywallRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/account/$pathname': typeof AccountPathnameRoute
}

interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof AuthLayoutRouteWithChildren
  '/(public)': typeof PublicLayoutRouteWithChildren
  '/(public)/sign-in': typeof PublicSignInRoute
  '/(public)/sign-up': typeof PublicSignUpRoute
  '/(auth)/(tabs)': typeof AuthTabsLayoutRouteWithChildren
  '/(auth)/(tabs)/orders/': typeof AuthTabsOrdersIndexRoute
  '/(auth)/(tabs)/menu/': typeof AuthTabsMenuIndexRoute
  '/(auth)/(tabs)/payments/': typeof AuthTabsPaymentsIndexRoute
  '/(auth)/(tabs)/guest-order/': typeof AuthTabsGuestOrderIndexRoute
  '/(auth)/(tabs)/profile/': typeof AuthTabsProfileIndexRoute
  '/(auth)/(tabs)/menu/add-meal': typeof AuthTabsMenuAddMealRoute
  '/(auth)/(tabs)/profile/edit': typeof AuthTabsProfileEditRoute
  '/(auth)/(tabs)/profile/settings': typeof AuthTabsProfileSettingsRoute
  '/(auth)/(tabs)/profile/categories': typeof AuthTabsProfileCategoriesRoute
  '/(auth)/(tabs)/profile/daily-report': typeof AuthTabsProfileDailyReportRoute
  '/(auth)/(tabs)/orders/details/$id': typeof AuthTabsOrdersDetailsIdRoute
  '/(auth)/(tabs)/payments/receipt/$id': typeof AuthTabsPaymentsReceiptIdRoute
  '/(auth)/(tabs)/profile/users/': typeof AuthTabsProfileUsersIndexRoute
  '/(auth)/(tabs)/profile/membership/': typeof AuthTabsProfileMembershipIndexRoute
  '/(auth)/(tabs)/profile/users/add-user': typeof AuthTabsProfileUsersAddUserRoute
  '/(auth)/(tabs)/profile/membership/paywall': typeof AuthTabsProfileMembershipPaywallRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/account/$pathname': typeof AccountPathnameRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/orders'
    | '/menu'
    | '/payments'
    | '/guest-order'
    | '/profile'
    | '/menu/add-meal'
    | '/profile/edit'
    | '/profile/settings'
    | '/profile/categories'
    | '/profile/daily-report'
    | '/orders/details/$id'
    | '/payments/receipt/$id'
    | '/profile/users'
    | '/profile/membership'
    | '/profile/users/add-user'
    | '/profile/membership/paywall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/orders'
    | '/menu'
    | '/payments'
    | '/guest-order'
    | '/profile'
    | '/menu/add-meal'
    | '/profile/edit'
    | '/profile/settings'
    | '/profile/categories'
    | '/profile/daily-report'
    | '/orders/details/$id'
    | '/payments/receipt/$id'
    | '/profile/users'
    | '/profile/membership'
    | '/profile/users/add-user'
    | '/profile/membership/paywall'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(public)'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(auth)/(tabs)'
    | '/(auth)/(tabs)/orders/'
    | '/(auth)/(tabs)/menu/'
    | '/(auth)/(tabs)/payments/'
    | '/(auth)/(tabs)/guest-order/'
    | '/(auth)/(tabs)/profile/'
    | '/(auth)/(tabs)/menu/add-meal'
    | '/(auth)/(tabs)/profile/edit'
    | '/(auth)/(tabs)/profile/settings'
    | '/(auth)/(tabs)/profile/categories'
    | '/(auth)/(tabs)/profile/daily-report'
    | '/(auth)/(tabs)/orders/details/$id'
    | '/(auth)/(tabs)/payments/receipt/$id'
    | '/(auth)/(tabs)/profile/users/'
    | '/(auth)/(tabs)/profile/membership/'
    | '/(auth)/(tabs)/profile/users/add-user'
    | '/(auth)/(tabs)/profile/membership/paywall'
    | '/auth/$pathname'
    | '/account/$pathname'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
  AccountPathnameRoute: AccountPathnameRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
