/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as GuestOrderIndexRouteImport } from './routes/guest-order/index'
import { Route as ProfileTablesRouteImport } from './routes/profile/tables'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileDailyReportRouteImport } from './routes/profile/daily-report'
import { Route as ProfileCategoriesRouteImport } from './routes/profile/categories'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'
import { Route as ProfileUsersIndexRouteImport } from './routes/profile/users/index'
import { Route as ProfileMembershipIndexRouteImport } from './routes/profile/membership/index'
import { Route as ProfileUsersAddUserRouteImport } from './routes/profile/users/add-user'
import { Route as ProfileMembershipPaywallRouteImport } from './routes/profile/membership/paywall'
import { Route as PaymentsReceiptIdRouteImport } from './routes/payments/receipt/$id'
import { Route as OrdersDetailsIdRouteImport } from './routes/orders/details/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOrderIndexRoute = GuestOrderIndexRouteImport.update({
  id: '/guest-order/',
  path: '/guest-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTablesRoute = ProfileTablesRouteImport.update({
  id: '/profile/tables',
  path: '/profile/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDailyReportRoute = ProfileDailyReportRouteImport.update({
  id: '/profile/daily-report',
  path: '/profile/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCategoriesRoute = ProfileCategoriesRouteImport.update({
  id: '/profile/categories',
  path: '/profile/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsersIndexRoute = ProfileUsersIndexRouteImport.update({
  id: '/profile/users/',
  path: '/profile/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMembershipIndexRoute = ProfileMembershipIndexRouteImport.update({
  id: '/profile/membership/',
  path: '/profile/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsersAddUserRoute = ProfileUsersAddUserRouteImport.update({
  id: '/profile/users/add-user',
  path: '/profile/users/add-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMembershipPaywallRoute =
  ProfileMembershipPaywallRouteImport.update({
    id: '/profile/membership/paywall',
    path: '/profile/membership/paywall',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentsReceiptIdRoute = PaymentsReceiptIdRouteImport.update({
  id: '/payments/receipt/$id',
  path: '/payments/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersDetailsIdRoute = OrdersDetailsIdRouteImport.update({
  id: '/orders/details/$id',
  path: '/orders/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/daily-report': typeof ProfileDailyReportRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tables': typeof ProfileTablesRoute
  '/guest-order/': typeof GuestOrderIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/orders/details/$id': typeof OrdersDetailsIdRoute
  '/payments/receipt/$id': typeof PaymentsReceiptIdRoute
  '/profile/membership/paywall': typeof ProfileMembershipPaywallRoute
  '/profile/users/add-user': typeof ProfileUsersAddUserRoute
  '/profile/membership/': typeof ProfileMembershipIndexRoute
  '/profile/users/': typeof ProfileUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/daily-report': typeof ProfileDailyReportRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tables': typeof ProfileTablesRoute
  '/guest-order': typeof GuestOrderIndexRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/orders/details/$id': typeof OrdersDetailsIdRoute
  '/payments/receipt/$id': typeof PaymentsReceiptIdRoute
  '/profile/membership/paywall': typeof ProfileMembershipPaywallRoute
  '/profile/users/add-user': typeof ProfileUsersAddUserRoute
  '/profile/membership': typeof ProfileMembershipIndexRoute
  '/profile/users': typeof ProfileUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/profile/categories': typeof ProfileCategoriesRoute
  '/profile/daily-report': typeof ProfileDailyReportRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tables': typeof ProfileTablesRoute
  '/guest-order/': typeof GuestOrderIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/orders/details/$id': typeof OrdersDetailsIdRoute
  '/payments/receipt/$id': typeof PaymentsReceiptIdRoute
  '/profile/membership/paywall': typeof ProfileMembershipPaywallRoute
  '/profile/users/add-user': typeof ProfileUsersAddUserRoute
  '/profile/membership/': typeof ProfileMembershipIndexRoute
  '/profile/users/': typeof ProfileUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/profile/categories'
    | '/profile/daily-report'
    | '/profile/edit'
    | '/profile/settings'
    | '/profile/tables'
    | '/guest-order/'
    | '/menu/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/orders/details/$id'
    | '/payments/receipt/$id'
    | '/profile/membership/paywall'
    | '/profile/users/add-user'
    | '/profile/membership/'
    | '/profile/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/profile/categories'
    | '/profile/daily-report'
    | '/profile/edit'
    | '/profile/settings'
    | '/profile/tables'
    | '/guest-order'
    | '/menu'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/orders/details/$id'
    | '/payments/receipt/$id'
    | '/profile/membership/paywall'
    | '/profile/users/add-user'
    | '/profile/membership'
    | '/profile/users'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/profile/categories'
    | '/profile/daily-report'
    | '/profile/edit'
    | '/profile/settings'
    | '/profile/tables'
    | '/guest-order/'
    | '/menu/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/orders/details/$id'
    | '/payments/receipt/$id'
    | '/profile/membership/paywall'
    | '/profile/users/add-user'
    | '/profile/membership/'
    | '/profile/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ProfileCategoriesRoute: typeof ProfileCategoriesRoute
  ProfileDailyReportRoute: typeof ProfileDailyReportRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileTablesRoute: typeof ProfileTablesRoute
  GuestOrderIndexRoute: typeof GuestOrderIndexRoute
  MenuIndexRoute: typeof MenuIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  OrdersDetailsIdRoute: typeof OrdersDetailsIdRoute
  PaymentsReceiptIdRoute: typeof PaymentsReceiptIdRoute
  ProfileMembershipPaywallRoute: typeof ProfileMembershipPaywallRoute
  ProfileUsersAddUserRoute: typeof ProfileUsersAddUserRoute
  ProfileMembershipIndexRoute: typeof ProfileMembershipIndexRoute
  ProfileUsersIndexRoute: typeof ProfileUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-order/': {
      id: '/guest-order/'
      path: '/guest-order'
      fullPath: '/guest-order/'
      preLoaderRoute: typeof GuestOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/tables': {
      id: '/profile/tables'
      path: '/profile/tables'
      fullPath: '/profile/tables'
      preLoaderRoute: typeof ProfileTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/daily-report': {
      id: '/profile/daily-report'
      path: '/profile/daily-report'
      fullPath: '/profile/daily-report'
      preLoaderRoute: typeof ProfileDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/categories': {
      id: '/profile/categories'
      path: '/profile/categories'
      fullPath: '/profile/categories'
      preLoaderRoute: typeof ProfileCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/users/': {
      id: '/profile/users/'
      path: '/profile/users'
      fullPath: '/profile/users/'
      preLoaderRoute: typeof ProfileUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/membership/': {
      id: '/profile/membership/'
      path: '/profile/membership'
      fullPath: '/profile/membership/'
      preLoaderRoute: typeof ProfileMembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/users/add-user': {
      id: '/profile/users/add-user'
      path: '/profile/users/add-user'
      fullPath: '/profile/users/add-user'
      preLoaderRoute: typeof ProfileUsersAddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/membership/paywall': {
      id: '/profile/membership/paywall'
      path: '/profile/membership/paywall'
      fullPath: '/profile/membership/paywall'
      preLoaderRoute: typeof ProfileMembershipPaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/receipt/$id': {
      id: '/payments/receipt/$id'
      path: '/payments/receipt/$id'
      fullPath: '/payments/receipt/$id'
      preLoaderRoute: typeof PaymentsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/details/$id': {
      id: '/orders/details/$id'
      path: '/orders/details/$id'
      fullPath: '/orders/details/$id'
      preLoaderRoute: typeof OrdersDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ProfileCategoriesRoute: ProfileCategoriesRoute,
  ProfileDailyReportRoute: ProfileDailyReportRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileTablesRoute: ProfileTablesRoute,
  GuestOrderIndexRoute: GuestOrderIndexRoute,
  MenuIndexRoute: MenuIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  OrdersDetailsIdRoute: OrdersDetailsIdRoute,
  PaymentsReceiptIdRoute: PaymentsReceiptIdRoute,
  ProfileMembershipPaywallRoute: ProfileMembershipPaywallRoute,
  ProfileUsersAddUserRoute: ProfileUsersAddUserRoute,
  ProfileMembershipIndexRoute: ProfileMembershipIndexRoute,
  ProfileUsersIndexRoute: ProfileUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
